#!/bin/bash
clear 
azul="\033[38;5;31m"
rojo="\033[38;1;31m"
verd="\033[38;0;32m"
purp="\033[38;1;35m"
amar="\033[38;1;33m"

model_engine="text-davinci-003"
key=$(sed 's/ //g' /data/data/com.termux/files/usr/bin/bot.txt)
api_key="$key"
mensaje=$1

btn=&& echo -e "         $azul<=======$amar[$purp BOT $amar]$azul=======>" && echo "" && echo -e "$rojo     el resultado de la busqueda  " && echo -e "  $amar    [$verd $mensaje$amar] $purp es " && echo "" && echo -e "$azul          ↓    ↓    ↓    ↓    ↓"
todo () {	
if [[ $mensaje == "" ]];then
	echo "      para usar el asistente escribe:"
	tput setaf 1;echo -n "         bot";tput setaf 10;echo ' mas la pregunta '
else
	respuesta=$(curl -s -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $api_key" https://api.openai.com/v1/engines/$model_engine/completions -d "{\"prompt\":\"$mensaje\",\"max_tokens\":1024,\"temperature\":0.5}" | jq -r '.choices[0].text' )
	if [[ $respuesta == "" ]] || [[ $respuesta == "no hay un resultado para su busqueda " ]];then
		tput setaf 1;echo "no hay conexion a internet o al servidor del bot"
		exit
	else
		tput setaf 1;echo -n "$btn:";tput setaf 10;echo -e "$respuesta"
	fi
fi
}

if [[ $btn = $btn ]];then                               todo                                      
else
	echo "Hubo un error, vuelve a instalar Bot"
fi
