#!/bin/bash
clear 

#codigos del creador no tocar 
creador=elias
usuario=$creador
cliente=$usuario=$creador=elias
usuario2=$usuario=$creador=$cliente="elias"


#colores 
azul="\033[38;5;31m"
rojo="\033[38;1;31m"
verd="\033[38;0;32m"
purp="\033[38;1;35m"
amar="\033[38;1;33m"

model_engine="text-davinci-003"
key=$(sed 's/ //g' /data/data/com.termux/files/usr/bin/bot.txt)
api_key="$key"
mensaje=$1
sin-coneccion(){
clear 
sl
echo -e "
$rojo┏━━━━━━━━━━━━$azul•A surguido un error$azul •$rojo━━━━━━━━━━━┓
┣ 🎩$verd Lo siento no hay coneccion a internet 🎩 $rojo┫
┣🎩$verd o al server del bot  Reintente mas tarde🎩$rojo┫
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

"
}
banner(){
echo -e "
$azul┏━━━━━━━━━━━━━━━━$purp•$rojo LG REYNA$purp •$azul━━━━━━━━━━━━━━━┓
┣━━━━❰･🎩$verd Espere buscando respuesta $azul🎩･❱━━━━┫
┗━━━━━━━━━━━━━•$amar Haking etico,$azul •━━━━━━━━━━━━━┛
"
}
btn=&& banner
todo () {	
if [[ $mensaje == "" ]];then
	echo "      para usar el asistente escribe:"
	tput setaf 1;echo -n "         bot";tput setaf 10;echo ' " y entre dobles comillas  pregunta "'|lolcat -a -d 2
else
	respuesta=$(curl -s -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $api_key" https://api.openai.com/v1/engines/$model_engine/completions -d "{\"prompt\":\"$mensaje\",\"max_tokens\":1024,\"temperature\":0.5}" | jq -r '.choices[0].text' )
	if [[ $respuesta == "" ]] || [[ $respuesta == "no hay un resultado para su busqueda " ]];then
		tput setaf 1; sin-coneccion 
		exit
	else
		tput setaf 1;echo -n "$btn:";tput setaf 10;echo -e "$respuesta"
	fi
fi
}

if [[ $usuario2 = "elias=elias=elias=elias=elias=elias" ]];then todo
else
clear
echo -e "
$azul┏━━━━━━━━━━━━━━━━━━━$purp•$verd LG REYNA$purp •$azul━━━━━━━━━━━━━━━━━━━━━━┓
$rojo re instalando al bot por midificasiones no permitidas
$azul┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
"
reinstalacion(){
apt update && apt upgrade -y

pkg install git

pkg install ruby

gem install lolcat

git clone https://github.com/ELIAS-1829/BOT

cd BOT

chmod +x install.sh

./install.sh
}

fi
